FROM arm32v7/python:3.8-buster

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN apt update && apt install -y python3-lxml python3-dev python3-cffi build-essential libffi-dev openssl libxml2-dev libxslt-dev libssl-dev cython libz-dev
RUN apt -y  install gcc 
RUN pip install --no-cache-dir -r requirements.txt
RUN apt install -y vim
COPY . .

CMD [ "python", "-u", "./CPU_temperature.py"]